export const SET_PROGRAM_ID = 'SET_PROGRAM_ID'
export const SET_POOL_ID = 'SET_POOL_ID'
export const SET_MINIMUM_STAKE_AMOUNT = 'SET_MINIMUM_STAKE_AMOUNT'
export const SET_USER_BALANCE = 'SET_USER_BALANCE'
export const SET_REWARD_AMOUNT = 'SET_REWARD_AMOUNT'
export const SET_STAKED_AMOUNT = 'SET_STAKED_AMOUNT'
export const SET_INDICATOR_STATUS = 'SET_INDICATOR_STATUS'
export const RESET_POOL = 'RESET_POOL'
export const RESET_INDICATORS = 'RESET_INDICATORS'
export const SET_STAKE_AMOUNT = 'SET_STAKE_AMOUNT'
export const SET_STAKE_ACCOUNT = 'SET_STAKE_ACCOUNT'
export const SET_STAKE_KEY = 'SET_STAKE_KEY'
export const SET_STAKER_ATA = 'SET_STAKER_ATA'
export const SET_POOL_DATA = 'SET_POOL_DATA'
export const SET_LOADING = 'SET_LOADING'
export const SET_RPC_ERROR = 'SET_RPC_ERROR'
export const SET_HAS_ACCESS = 'SET_HAS_ACCESS'

// Loading Indicator Messages
export const ACCOUNT_CHECKING = 'Looking for a staking account...'
export const ACCOUNT_CREATING = 'Creating a staking account...'
export const ACCOUNT_CREATED = 'Successfully created a staking account!'
export const ACCOUNT_FOUND = 'Found a staking account!'

export const REWARDS_CLAIMING = 'Claiming rewards...'
export const REWARDS_CLAIMED = 'Rewards claimed!'

export const STAKE_STAKING = 'Staking tokens...'
export const STAKE_STAKED = 'Successfully staked tokens!'

export const ERROR_MESSAGE = 'There was an error'
