export const SET_PROGRAM_ID = 'SET_PROGRAM_ID'
export const SET_CONNECTION = 'SET_CONNECTION'
export const SET_CENTRAL_STATE = 'SET_CENTRAL_STATE'
export const SET_UNSTAKE_REDIRECT_URL = 'SET_UNSTAKE_REDIRECT_URL'
